#1 Download ubuntu 20.04
FROM ubuntu:20.04

#No interaction while installing or upgrading the system via apt.
#It accepts the default answer for all questions.
ENV DEBIAN_FRONTEND=noninteractive

#2 Install all packages that are needed to run your program,
#  such as vim, git, java 11, maven, etc.

#3 Create /root/project folder and set it as WORKDIR.
RUN mkdir -p /root/project
WORKDIR /root/project

RUN  apt-get update \
  && apt-get install -y wget
  #&& rm -rf /var/lib/apt/lists/*
#RUN wget https://mirror.navercorp.com/apache/tomcat/tomcat-8/v8.5.68/bin/apache-tomcat-8.5.68.tar.gz
#RUN tar -xvzf apache-tomcat-8.5.68.tar.gz

#RUN apt-get install -y --no-install-recommends apt-utils
RUN apt-get install -y git
RUN apt-get install -y maven
RUN apt-get install -y default-jdk
RUN apt-get install -y curl
RUN apt-get install -y vim
RUN wget https://mirror.navercorp.com/apache/tomcat/tomcat-8/v8.5.68/bin/apache-tomcat-8.5.68.tar.gz
RUN tar -xvzf apache-tomcat-8.5.68.tar.gz
        #iputils-ping \
        #net-tools

RUN apt-get install -y gnupg
RUN wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | apt-key add -
RUN echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-4.4.list
RUN apt-get install -y mongodb
RUN mkdir -p /data/db/
RUN chown root /data/db
#RUN mongod --fork --logpath /var/log/mongodb.log


ENV JAVA_HOME /usr/lib/jvm/java-11-openjdk-amd64/
ENV PATH $PATH:$JAVA_HOME/bin


ADD run.sh /root/project
#RUN cd /root/project


ADD cse364-project.war /root/project/apache-tomcat-8.5.68/webapps
#WORKDIR /root/project
#RUN /root/project/apache-tomcat-8.5.68/bin/catalina.sh start
#RUN ./catalina.sh start
#CMD ["/bin/bash/"]
EXPOSE 8080

CMD /root/project/apache-tomcat-8.5.68/bin/catalina.sh run


#5 Execute a bash shell by default when the built image is launched.
#ENTRYPOINT ["/bin/bash"]
