#1 Download ubuntu 20.04
FROM ubuntu:20.04

#2 Install all packages that are needed to run your program,
#  such as vim, git, java 11, maven, etc.

#No interaction while installing or upgrading the system via apt.
#It accepts the default answer for all questions.
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install -y \
	vim \
	git \
	default-jdk \
	maven \
	locales

#locales pkg enables to comment in korean
RUN locale-gen ko_KR.UTF-8

ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
ENV LC_ALL ko_KR.UTF-8

#3 Create /root/project folder and set it as WORKDIR.
RUN mkdir -p /root/project
WORKDIR /root/project

#4 Add your run.sh file to /root/project in the docker container.
ADD run.sh /root/project

#5 Execute a bash shell by default when the built image is launched.
ENTRYPOINT ["/bin/bash"]