name: Docker

on:

  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout private tools
      uses: actions/checkout@v2
      with:
        repository: my-org/my-private-tools
        token: ${{ secrets.GitHub_PAT }} # `GitHub_PAT` is a secret that contains your PAT
        path: my-tools
    
    - name: Docker Setup QEMU (Docker install)
      uses: docker/setup-qemu-action@v1.2.0
      
    - name: Build and run Docker image and mvn test
      run: | 
         cd scripts
         docker build -t docker_image_by_workflow .
         docker run -it docker_image_by_workflow
         git clone https://7431831df8332ebd730fab69f7dbdc329659ed45@github.com/sirin05137/CSE364_Project.git
         cd CSE364_Project
         mvn test
