name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build,run the Docker image and mvn test
      run: |
      docker build -t docker_image_by_workflow .
      docker run -it docker_image_by_workflow
      git clone https://7431831df8332ebd730fab69f7dbdc329659ed45@github.com/sirin05137/CSE364_Project.git
      cd CSE364_Project
      mvn test
