name: mvn test in Docker container

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Clone sirin05137/CSE364_Project
      uses: actions/checkout@v2
      with:
        token: secrets.GROUP11
    
    - name: docker install
      uses: docker/setup-qemu-action@v1.2.0
      
    - name: build docker image 
      run: | 
         cd scripts
         docker build -t docker_image_by_workflow .
         
    - name: docker Run & mvn test in container 
      uses: addnab/docker-run-action@v3
      with:
        image: docker_image_by_workflow
        run: |
           git clone https://7431831df8332ebd730fab69f7dbdc329659ed45@github.com/sirin05137/CSE364_Project.git
           cd CSE364_Project
           mvn test
