name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check_private_repo
      uses: actions/checkout@v2
      with:
        token: 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 # `GitHub_PAT` is a secret that contains your PAT
    
    - name: Docker Setup QEMU (Docker install)
      uses: docker/setup-qemu-action@v1.2.0
      
    - name: Build and run Docker image 
      run: | 
         cd scripts
         docker build -t docker_image_by_workflow .
         docker exec -it docker_image_by_workflow bash
         
    - name: In docker, mvn test
      run: | 
         git clone https://7431831df8332ebd730fab69f7dbdc329659ed45@github.com/sirin05137/CSE364_Project.git
         cd CSE364_Project
         mvn test
